# Generated by Django 4.0.3 on 2022-03-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_genre_artist_spotify_uri_artist_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='image_url',
            new_name='avatar_img',
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='artist',
            name='header_img',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
