# Generated by Django 4.0.3 on 2022-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_album_date_alter_artist_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
