# Generated by Django 4.0.3 on 2022-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_album_artist_artist_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['world_rank']},
        ),
        migrations.AddField(
            model_name='artist',
            name='world_rank',
            field=models.IntegerField(default=9999999),
        ),
    ]
