# Generated by Django 4.0.3 on 2022-03-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_artist_options_artist_world_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
