# Generated by Django 4.0.3 on 2022-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_artist_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
