# Generated by Django 4.0.3 on 2022-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_album_artist_album_owners_delete_artist_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
    ]
